spring:
  application:
    name: gateway-service
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa 
    password: password
  jpa: 
    database-platform: org.hibernate.dialect.H2Dialect
  h2: 
    console:
      enabled: true
      
server:
  port: 9000
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: false
