spring:
  application:
    name: doctor
  datasource:
    url: jdbc:h2:file:C:/Users/353835/health-manager-data/doctor
    driverClassName: org.h2.Driver
    username: sa 
    password: password
  jpa: 
    database-platform: org.hibernate.dialect.H2Dialect
  h2: 
    console:
      enabled: true

---

spring:
  profiles: dev
  
server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: false

---

spring:
  profiles: test
  cloud:
    discovery:  
        enabled: false
