--Doctor table--
CREATE CACHED TABLE "PUBLIC"."DOCTOR"(
    "ID" BIGINT NOT NULL,
    "ADDRESS1" VARCHAR(255),
    "ADDRESS2" VARCHAR(255),
    "DATE_OF_BIRTH" TIMESTAMP,
    "DEPARTMENT" VARCHAR(255),
    "DISTRICT" VARCHAR(255),
    "EMAIL" VARCHAR(255),
    "NAME" VARCHAR(255),
    "ORGANISATION" VARCHAR(255),
    "PHONE_NUMBER" VARCHAR(255),
    "SALUTATION" VARCHAR(255),
    "STATE" VARCHAR(255),
    "ZIP_CODE" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."DOCTOR" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("ID");